version: '3.8'

volumes:
  dbdata_test:  

services:
  mysql_test:
    container_name: mysql_test
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql/conf.d:/etc/mysql/conf.d
      - ./data/mysql/initdb.d:/docker-entrypoint-initdb.d
      - dbdata_test:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}_test
      - MYSQL_USER=${MYSQL_USER}_test
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT_TEST}:3306         
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - ${ADMINER_LOCAL_PORT}:8080   
    depends_on:
      - mysql_test   
