package repos;

import com.google.inject.Inject;
import exceptions.DbException;
import exceptions.ModelException;
import models.band.Band;
import models.band.BandSchema;
import services.BandService;
import utils.Db;

import java.sql.*;
import java.util.logging.Logger;

public class BandRepo implements BandService {
    private static final Logger logger = Logger.getLogger(BandRepo.class.getName());
    @Inject private Db db;
    @Inject private BandSchema schema;

    /**
     * Return a band by its primary key
     *
     * @param id Band's primary key
     * @return Band
     */
    @Override
    public Band getById(long id) {
        String sql = String.format(
            "SELECT * FROM %s WHERE id = ?", schema.tableName()
        );
        try (
                Connection conn = db.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql);
        ) {
            stmt.setLong(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return schema.getModelFromResultSet(rs);
                }

                return null;
            }
        } catch (SQLException e) {
            logger.severe(e.getMessage());
            throw new DbException("Cannot get the band", DbException.SQL_EXCEPTION);
        }
    }

    /**
     * Upsert of a band into the database
     *
     * @param band The band.
     * @return The band
     */
    @Override
    public Band save(Band band) {
        if (!band.isValid()) {
            throw new ModelException(band.getErrors(), band.getErrorCode());
        }

        String sql;

        if (band.getId() != null) { // update
            sql = schema.getSqlForUpdate();

            try (
                Connection conn = db.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql);
            ) {
                schema.setStatementValues(stmt, band);
                int affectedRows = stmt.executeUpdate();
                logger.info("Band.save, affected rows: " + affectedRows);

                if (affectedRows == 0) {
                    throw new DbException(
                        "No band found with id " + band.getId(),
                        DbException.RESOURCE_NOT_FOUND
                    );
                }

                return band;
            } catch (SQLException e) {
                logger.severe(e.getMessage());
                throw new DbException("Cannot get the band", DbException.SQL_EXCEPTION);
            }

        } else { // create
            sql = schema.getSqlForInsert();
            int autoGeneratedKeys = Statement.RETURN_GENERATED_KEYS;

            try (
                Connection conn = db.getConnection();
                PreparedStatement stmt = conn.prepareStatement(sql, autoGeneratedKeys);
            ) {
                schema.setStatementValues(stmt, band);
                int affectedRows = stmt.executeUpdate();
                logger.info("Band.save, affected rows: " + affectedRows);

                if (affectedRows == 0) {
                    throw new DbException(
                            "Insert new band failed",
                            DbException.SQL_EXCEPTION
                    );
                }

                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        band.setId(generatedKeys.getLong(1));
                        return band;
                    } else {
                        throw new SQLException("Creating band failed, no ID obtained.");
                    }
                }
            } catch (SQLException e) {
                logger.severe(e.getMessage());
                throw new DbException("Cannot get the band", DbException.SQL_EXCEPTION);
            }
        }
    }
}
