package repos;

import com.google.inject.Inject;
import exceptions.DbException;
import exceptions.ModelException;
import models.files.MusicFile;
import models.files.MusicFileSchema;
import services.MusicFileService;
import utils.Db;

import java.sql.*;
import java.util.logging.Logger;

public class MusicFileRepo implements MusicFileService {
    private static final Logger logger = Logger.getLogger(MusicFileRepo.class.getName());
    @Inject private Db db;
    @Inject private MusicFileSchema schema;

    /**
     * Return a file by its primary key
     *
     * @param id file's primary key
     * @return MusicFile
     */
    @Override
    public MusicFile getById(long id) {
        String sql = String.format(
          "SELECT * FROM %s WHERE id = ?", schema.tableName()
        );
        try (
          Connection conn = db.getConnection();
          PreparedStatement stmt = conn.prepareStatement(sql);
        ) {
            stmt.setLong(1, id);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    return schema.getModelFromResultSet(rs);
                }

                return null;
            }
        } catch (SQLException e) {
            logger.severe(e.getMessage());
            throw new DbException("Cannot get the file", DbException.SQL_EXCEPTION);
        }
    }

    /**
     * Upsert of a file into the database
     *
     * @param file The file.
     * @return The file
     */
    @Override
    public MusicFile save(MusicFile file) {
        if (!file.isValid()) {
            throw new ModelException(file.getErrors(), file.getErrorCode());
        }

        String sql;

        if (file.getId() != null) { // update
            sql = schema.getSqlForUpdate();

            try (
              Connection conn = db.getConnection();
              PreparedStatement stmt = conn.prepareStatement(sql);
            ) {
                schema.setStatementValues(stmt, file);
                int affectedRows = stmt.executeUpdate();
                logger.info("Band.update, affected rows: " + affectedRows);

                if (affectedRows == 0) {
                    throw new DbException(
                      String.format("No file with id %d was found", file.getId()),
                      DbException.RESOURCE_NOT_FOUND
                    );
                }

                return file;
            } catch (SQLException e) {
                logger.severe(e.getMessage());
                throw new DbException("Updating the file failed", DbException.SQL_EXCEPTION);
            }

        } else { // create
            sql = schema.getSqlForInsert();
            int autoGeneratedKeys = Statement.RETURN_GENERATED_KEYS;

            try (
              Connection conn = db.getConnection();
              PreparedStatement stmt = conn.prepareStatement(sql, autoGeneratedKeys);
            ) {
                schema.setStatementValues(stmt, file);
                int affectedRows = stmt.executeUpdate();
                logger.info("file.create, affected rows: " + affectedRows);

                if (affectedRows == 0) {
                    throw new DbException(
                      "Insert new file failed",
                      DbException.SQL_EXCEPTION
                    );
                }

                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        file.setId(generatedKeys.getLong(1));
                        return file;
                    } else {
                        throw new SQLException("Creating file failed, no ID obtained.");
                    }
                }
            } catch (SQLException e) {
                logger.severe(e.getMessage());
                throw new DbException("Cannot get the file", DbException.SQL_EXCEPTION);
            }
        }
    }

    /**
     * Delete a file.
     *
     * @param id The file's id.
     * @return true if the operation was successful, false otherwise.
     */
    @Override
    public boolean delete(long id) {
        return false;
    }
}